=== JamesHallowell/OcaToolsAndDemos/OCACompliancyTestTool/Aes70CompliancyTestTool/Xml/ReferenceOCCMembers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="OcaDevice" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
  <!-- Define how the versions structure looks like -->
  <xs:element name="Versions">
    <xs:complexType>
      <xs:sequence>
        <!-- Define a single version -->
        <xs:element name="Version" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:attribute name="OcaVersion" type="xs:string"/>
            <xs:attribute name="ClassVersion" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Mandatory map within the class -->
  <xs:element name="MandatoryMap">
    <xs:complexType>
      <xs:sequence>
        <!-- Single mandatory item -->
        <xs:element name="Mandatory" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="OcaVersion" type="xs:string"/>
            <xs:attribute name="Mandatory" type="xs:string"/>
			<xs:attribute name="DeviceType" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Define how the methods structure looks like -->
  <xs:element name="Methods">
    <xs:complexType>
      <xs:sequence>
        <!-- Define how a single method looks like -->
        <xs:element name="Method" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- Mandatory map within the method -->
              <xs:element name="MandatoryMap" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <!-- Single mandatory item -->
                    <xs:element name="Mandatory" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="OcaVersion" type="xs:string"/>
                        <xs:attribute name="Mandatory" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string"/>
            <xs:attribute name="Index" type="xs:string"/>
            <xs:attribute name="AvailableSince" type="xs:string"/>
            <xs:attribute name="DeprecatedSince" type="xs:string"/>
            <xs:attribute name="ConnectionType" type="xs:string"/>
            <xs:attribute name="RequiredDeviceType" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Define how the events structure looks like -->
  <xs:element name="Events">
    <xs:complexType>
      <xs:sequence>
        <!-- Define how a single events looks like  -->
        <xs:element name="Event" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- Mandatory map within the event -->
              <xs:element name="MandatoryMap" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <!-- Single mandatory item -->
                    <xs:element name="Mandatory" minOccurs="0" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:attribute name="OcaVersion" type="xs:string"/>
                        <xs:attribute name="Mandatory" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Name" type="xs:string"/>
            <xs:attribute name="Index" type="xs:string"/>
            <xs:attribute name="AvailableSince" type="xs:string"/>
            <xs:attribute name="DeprecatedSince" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <!-- Root structure -->
  <xs:element name="OcaDevice" msdata:IsDataSet="true" msdata:Locale="en-US">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="Methods" />
        <xs:element ref="Events" />
        <xs:element ref="Versions" />
        <xs:element ref="MandatoryMap" />
        <!-- OcaRoot -->
        <xs:element name="Root" maxOccurs="1" minOccurs="1">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="Versions" minOccurs="0" maxOccurs="1" />
              <xs:element ref="MandatoryMap" minOccurs="0" maxOccurs="1" />
              <xs:element ref="Methods" minOccurs="0" maxOccurs="1" />
              <xs:element ref="Events" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
            <xs:attribute name="Label" type="xs:string"/>
            <xs:attribute name="Name" type="xs:string"/>
            <xs:attribute name="ClassID" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        <!-- OcaManager -->
        <xs:element name="Managers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Manager" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="Versions" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="MandatoryMap" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="Methods" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="Events" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string"/>
                  <xs:attribute name="ClassID" type="xs:string"/>
                  <xs:attribute name="AvailableSince" type="xs:string"/>
                  <xs:attribute name="DeprecatedSince" type="xs:string"/>
                  <xs:attribute name="ObjNumber" type="xs:string"/>
                  <xs:attribute name="RequiredDeviceType" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Label" type="xs:string"/>
          </xs:complexType>
        </xs:element>
        <!-- OcaBlockMembers -->
        <xs:element name="BlockMembers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="BlockMember" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element ref="Versions" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="MandatoryMap" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="Methods" minOccurs="0" maxOccurs="1" />
                    <xs:element ref="Events" minOccurs="0" maxOccurs="1" />
                  </xs:sequence>
                  <xs:attribute name="Name" type="xs:string"/>
                  <xs:attribute name="ClassID" type="xs:string"/>
                  <xs:attribute name="AvailableSince" type="xs:string"/>
                  <xs:attribute name="DeprecatedSince" type="xs:string"/>
                  <xs:attribute name="RequiredDeviceType" type="xs:string"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="Label" type="xs:string"/>
            <xs:attribute name="ObjectNumberLowerLimit" type="xs:string"/>
            <xs:attribute name="ObjectNumberUpperLimit" type="xs:string"/>
          </xs:complexType>
        </xs:element>
      </xs:choice>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JamesHallowell/OcaToolsAndDemos/OCACompliancyTestTool/Aes70CompliancyTestTool/Xml/ReferenceOCCMembers.xml
<?xml version="1.0" encoding="utf-8"?>
<OcaDevice xmlns:occmembers="http://www.w3.org/2001/XMLSchema-instance" occmembers:noNamespaceSchemaLocation="ReferenceOCCMembers.xsd">
    <!-- Root segment[1]:
            Anything specific to both Managers and RootBlocks can be added here-->
    <Root Label="Root" Name="OcaRoot" ClassID="1">
        <Versions>
            <Version OcaVersion="AES70-2015" ClassVersion="1"/>
            <Version OcaVersion="AES70-2018" ClassVersion="2"/>
        </Versions>
        <Methods>
            <Method Name="GetClassIdentification" Index="1">
                <MandatoryMap>
                    <!-- Mandatory from OCA version AES70-2015 -->
                    <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                </MandatoryMap>
            </Method>
            <Method Name="GetLockable" Index="2">
                <MandatoryMap>
                    <!-- Mandatory from OCA version AES70-2015 -->
                    <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                </MandatoryMap>
            </Method>
            <Method Name="Lock" Index="3">
                <MandatoryMap>
                    <!-- Mandatory from OCA version AES70-2015, only if lockable -->
                    <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                </MandatoryMap>
            </Method>
            <Method Name="Unlock" Index="4">
                <MandatoryMap>
                    <!-- Mandatory from OCA version AES70-2015, only if lockable -->
                    <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                </MandatoryMap>
            </Method>
            <Method Name="GetRole" Index="5"  />
            <Method Name="LockReadOnly" Index="6" AvailableSince="AES70-2018" />
        </Methods>
        <Events>
            <Event Name="PropertyChanged" Index="1">
                <MandatoryMap>
                    <!-- Mandatory from OCA version AES70-2015 -->
                    <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                </MandatoryMap>
            </Event>
        </Events>
    </Root>
    <!-- Managers segment[2]:
            Anything specific to managers can be added here as an attribute -->
    <Managers Label="Managers">
        <!-- OcaManager doesn't contain any method -->
        <!-- OcaRoot.OcaManager -->
        <Manager Name="OcaManager" ClassID="1.3">
        </Manager>
        <!-- OcaRoot.OcaManager.OcaDeviceManager -->
        <Manager Name="OcaDeviceManager" ClassID="1.3.1" ObjNumber="1">
            <MandatoryMap>
                <!-- Mandatory from OCA version AES70-2015 -->
                <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
            </MandatoryMap>
            <Methods>
                <Method Name="GetOcaVersion" Index="1">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetModelGUID" Index="2">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetSerialNumber" Index="3">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetDeviceName" Index="4">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetModelDescription" Index="6">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetEnabled" Index="11">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="SetEnabled" Index="12">
                    <MandatoryMap>
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetState" Index="13">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetManagers" Index="19">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="GetDeviceRevisionID" Index="20" AvailableSince="AES70-2018">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2018 -->
                        <Mandatory OcaVersion="AES70-2018" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <!-- Optional members -->
                <Method Name="SetDeviceName" Index="5" />
                <Method Name="GetDeviceRole" Index="7" />
                <Method Name="SetDeviceRole" Index="8" />
                <Method Name="GetUserInventoryCode" Index="9" />
                <Method Name="SetUserInventoryCode" Index="10" />
                <Method Name="SetResetKey" Index="14" />
                <Method Name="GetResetCause" Index="15" />
                <Method Name="ClearResetCase" Index="16" />
                <Method Name="GetMessage" Index="17" />
                <Method Name="SetMessage" Index="18" />
            </Methods>
        </Manager>
        <!-- OcaRoot.OcaManager.OcaSecurityManager -->
        <Manager Name="OcaSecurityManager" ClassID="1.3.2" ObjNumber="2">
            <MandatoryMap>
                <!-- Not mandatory from OCA version AES70-2015 -->
                <Mandatory OcaVersion="AES70-2015" Mandatory="true" DeviceType="Secure"/>
            </MandatoryMap>
            <Methods>
                <Method Name="EnableControlSecurity" Index="1" ConnectionType="Secure">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="DisableControlSecurity" Index="2" ConnectionType="Secure">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="ChangePreSharedKey" Index="3" ConnectionType="Secure">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="AddPreSharedKey" Index="4" ConnectionType="Secure">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
                <Method Name="DeletePreSharedKey" Index="5" ConnectionType="Secure">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
            </Methods>
        </Manager>
        <!-- OcaRoot.OcaManager.OcaFirmwareManager -->
        <Manager Name="OcaFirmwareManager" ClassID="1.3.3" ObjNumber="3">
            <MandatoryMap>
                <!-- Mandatory from OCA version AES70-2015 -->
                <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                 <!-- No longer mandatory from OCA version AES70-2018 -->
                <Mandatory OcaVersion="AES70-2018" Mandatory="false"/>
            </MandatoryMap>
            <Methods>
                <Method Name="GetComponentVersions" Index="1">
                    <MandatoryMap>
                        <!-- Mandatory from OCA version AES70-2015 -->
                        <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                    </MandatoryMap>
                </Method>
            </Methods>
        </Manager>
        <!-- OcaRoot.OcaManager.OcaSubscriptionManager -->
        <Manager Name="OcaSubscriptionManager" ClassID="1.3.4" ObjNumber="4">
            <MandatoryMap>
                <!-- Mandatory from OCA version AES70-2015 -->
                <Mandatory OcaVersion="AES70-2015" Mandatory="true"/>
                <!-- No longer mandatory from OCA version AES70-2018-->
                <Mandatory OcaVersion="AES70-2018" Mandatory="false"/>
            </MandatoryMap>
